### ISSUE TITLE
在同一个form中同时使用两个markdown编辑器，最后存取的值一样

### ISSUE THREAD

**Issue by JKooll** [laravel-admin-extensions/simplemde#2]
![image](https://user-images.githubusercontent.com/10582881/49496864-ae7b8d80-f8b2-11e8-8554-7c42ff4e4925.png)
我在同一个form中使用了，在两个不同字段上使用了markdown编辑器，最后保存的值相同。

**Comment by z-song** [comment]
贴一下代码看看

**Comment by JKooll** [comment]
![image](https://user-images.githubusercontent.com/10582881/49497967-5eea9100-f8b5-11e8-8b53-8fde53fbbeda.png)
这种情况下，当修改summary中的内容的时候，提交之后，content中的内容会覆盖summary中的内容

**Comment by z-song** [comment]
@JKooll 确实有这个问题，已经提交了修复，稍后更新到版本`v1.0.1`

**Comment by JKooll** [comment]
谢啦
